export const ROUTES = {
  LOGIN: "/login",
  DASHBOARD: "/dashboard",
  QUESTIONS: "/questions",
  QUESTION_DETAILS: "/questions/:id",
  QUIZES: "/quizes",
  QUIZ_DETAILS: "/quizes/:id",
  CONTENT: "/content",
  MICRO_LEARNING: "/micro-learning",
  CONTENT_TO_REEL: "/edu-reels",
  CONTENT_CREATION: "/content-creation",
  CONTENT_DETAILS: "/content/:id",
  HOW_TO_USE: "/",
  NOT_FOUND: "*",
};
